@extends('site.layouts.basic')

@section('titulo', $titulo)

@section('bloco_conteudo')

<div class="container my-5">
  <div class="accordion" id="accordionPanelsStayOpenExample">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
            A TERRITORIALIZAÇÃO DO RACISMO AMBIENTAL EM COMUNIDADES QUILOMBOLAS DO MUNICÍPIO DE SEABRA - BAHIA
          </button>
        </h2>
        <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
          <div class="accordion-body">
            <strong>Trecho de artigo em português.</strong> Este trecho de artigo aborda como a mineração, a agricultura e a energia, principalmente eólica e solar, impactam diretamente as comunidades quilombolas, com foco na região de Seabra, na Chapada Diamantina, Bahia. A análise revela como a expansão desses setores, frequentemente vista como "desenvolvimento", se alinha ao racismo ambiental, onde as comunidades negras, como as quilombolas, são tratadas como "não-cidadãos" ou "entraves" ao progresso.
            O conceito de racismo ambiental é discutido, baseando-se na definição de Selene Herculano (2006), que relaciona a degradação ambiental e humana aos efeitos do desenvolvimento econômico, naturalizando a exploração das populações marginalizadas, como negros e indígenas. A obra também cita a ideia de "zonas de sacrifício", um termo que descreve áreas onde o capital explora intensamente os recursos naturais, levando a um empobrecimento ambiental e social, sem distribuir equitativamente os benefícios ou os impactos.
            Em Seabra, três grandes empreendimentos são destacados: a instalação de uma barragem, a chegada de mineradoras e o avanço de projetos eólicos. A construção da Barragem Vazante/Baraúnas afeta a comunidade quilombola da Vazante, causando deslocamento e uma luta constante por infraestrutura básica, como água e energia. As mineradoras, como a que atua na extração de mármore na comunidade do Morro Redondo, trazem impactos irreversíveis, como a destruição de paisagens, e afetam a qualidade de vida local, especialmente durante os períodos de atividade.
            Além disso, o setor eólico, em expansão na região, também afeta diretamente a comunidade quilombola do Morro Redondo, cuja titulação do território está em processo. Há preocupações sobre a interferência das empresas no processo de titulação e o impacto do avanço eólico sobre a terra da comunidade. Esse cenário é visto como uma forma de racismo ambiental, onde o avanço do capital, especialmente de grandes empresas de setores como mineração e energia, compromete a autonomia das comunidades quilombolas.
            O artigo conclui que essas ações estão imersas na lógica colonial do capitalismo, onde as comunidades tradicionais, principalmente as negras, são forçadas a sacrificar suas terras e modos de vida em nome do progresso econômico, e como essas práticas refletem o racismo ambiental, não necessariamente através de intenções explícitas de discriminação, mas por seus impactos raciais.
            Em resumo, o texto critica como esses setores, muitas vezes justificados como motores de desenvolvimento e geração de emprego, impõem um custo ambiental e social elevado sobre as comunidades quilombolas, exacerbando a desigualdade e a marginalização histórica desses grupos.
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
            THE TERRITORIALIZATION OF ENVIRONMENTAL RACISM IN QUILOMBOLA COMMUNITIES IN THE MUNICIPALITY OF SEABRA - BAHIA
          </button>
        </h2>
        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em inglês.</strong> This article discusses how mining, agriculture, and energy production—primarily wind and solar—directly impact quilombola communities, focusing on the region of Seabra in Chapada Diamantina, Bahia. The analysis highlights how the expansion of these sectors, often framed as "development," aligns with environmental racism, where Black communities, such as quilombolas, are treated as "non-citizens" or "obstacles" to progress.
            The concept of environmental racism is examined, drawing on Selene Herculano's (2006) definition, which links environmental and human degradation to the effects of economic development, normalizing the exploitation of marginalized populations, including Black and Indigenous peoples. The work also references the idea of "sacrifice zones," a term describing areas where capital intensively exploits natural resources, leading to environmental and social impoverishment without equitably distributing the benefits or burdens.
            In Seabra, three major projects are highlighted: the construction of a dam, the arrival of mining companies, and the expansion of wind energy projects. The construction of the Vazante/Baraúnas Dam affects the quilombola community of Vazante, causing displacement and an ongoing struggle for basic infrastructure, such as access to water and energy. Mining companies, such as those extracting marble in the Morro Redondo community, have caused irreversible impacts, including the destruction of landscapes and the deterioration of local living conditions, particularly during periods of operation.
            Additionally, the wind energy sector, which is expanding in the region, directly impacts the quilombola community of Morro Redondo, whose land titling process is still underway. Concerns exist regarding corporate interference in the land titling process and the effects of wind energy development on the community's territory. This situation is viewed as a form of environmental racism, where the advancement of capital, particularly by large companies in sectors like mining and energy, undermines the autonomy of quilombola communities.
            The article concludes that these actions are entrenched in the colonial logic of capitalism, forcing traditional communities, especially Black ones, to sacrifice their lands and ways of life in the name of economic progress. These practices exemplify environmental racism, not necessarily through explicit discriminatory intent but through their racialized impacts.
            In summary, the text critiques how these sectors, often justified as engines of development and job creation, impose significant environmental and social costs on quilombola communities, exacerbating the historical inequality and marginalization of these groups.
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
            LA TERRITORIALIZACIÓN DEL RACISMO AMBIENTAL EN LAS COMUNIDADES QUILOMBOLAS DEL MUNICIPIO DE SEABRA - BAHIA
          </button>
        </h2>
        <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em espanhol.</strong> El extracto de este artículo aborda cómo la minería, la agricultura y la energía, principalmente eólica y solar, impactan directamente a las comunidades quilombolas, centrándose en la región de Seabra, en Chapada Diamantina, Bahía. El análisis revela cómo la expansión de estos sectores, a menudo vistos como "desarrollo", se alinea con el racismo ambiental, donde las comunidades negras, como los quilombolas, son tratadas como "no ciudadanos" u "obstáculos" para el progreso.
            Se discute el concepto de racismo ambiental, a partir de la definición de Selene Herculano (2006), que relaciona la degradación ambiental y humana con los efectos del desarrollo económico, naturalizando la explotación de poblaciones marginadas, como los negros y los indígenas. El trabajo también menciona la idea de "zonas de sacrificio", término que describe áreas donde el capital explota intensivamente los recursos naturales, llevando al empobrecimiento ambiental y social, sin distribuir equitativamente los beneficios o impactos.
            En Seabra se destacan tres grandes novedades: la instalación de una presa, la llegada de empresas mineras y el avance de proyectos eólicos. La construcción de la presa Vazante/Baraúnas afecta a la comunidad quilombola de Vazante, provocando desplazamientos y una lucha constante por infraestructuras básicas, como agua y energía. Las empresas mineras, como la que extrae mármol en la comunidad de Morro Redondo, traen impactos irreversibles, como la destrucción de paisajes, y afectan la calidad de vida local, especialmente durante los períodos de actividad.
            Además, el sector eólico, en expansión en la región, también afecta directamente a la comunidad quilombola de Morro Redondo, cuyo título territorial está en trámite. Existen preocupaciones sobre la interferencia de las empresas en el proceso de titulación y el impacto del desarrollo eólico en las tierras de la comunidad. Este escenario es visto como una forma de racismo ambiental, donde el avance del capital, especialmente de las grandes empresas en sectores como la minería y la energía, compromete la autonomía de las comunidades quilombolas.
            El artículo concluye que estas acciones están inmersas en la lógica colonial del capitalismo, donde las comunidades tradicionales, especialmente las negras, se ven obligadas a sacrificar sus tierras y formas de vida en nombre del progreso económico, y como estas prácticas reflejan racismo ambiental, no necesariamente a través de intenciones explícitas de discriminación, sino a través de sus impactos raciales.
            En resumen, el texto critica cómo estos sectores, a menudo justificados como motores de desarrollo y creación de empleo, imponen un alto costo ambiental y social a las comunidades quilombolas, exacerbando la desigualdad y la marginación histórica de estos grupos.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">
            Racismo Ambiental: Colonialidade na Exploração Territorial
          </button>
        </h2>
        <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em português.</strong> O texto discute a ascensão do neoliberalismo nas décadas de 1990 e 2000, período em que o capitalismo global experimentou uma fase de superacumulação e reorganização, caracterizada pela diminuição do papel do Estado em áreas sociais e pelo incentivo ao livre mercado e ao consumo em escala global. Durante esse período, políticas públicas passaram a ser desvalorizadas, com cortes em gastos sociais como saúde, educação e segurança pública, o que resultou em uma maior desigualdade social e pobreza em diversas regiões, apesar do crescimento econômico global. Ao mesmo tempo, a destruição do meio ambiente se intensificou, com a exploração desenfreada de recursos naturais, especialmente nos países periféricos, o que gerou um aumento nas emissões de gases do efeito estufa e um impacto significativo no aquecimento global.
            O neoliberalismo se consolidou com a promoção de uma economia de mercado sem fronteiras, estimulada pela globalização e pelo avanço tecnológico. As grandes economias emergentes, como Brasil, Rússia, Índia e China, desempenharam um papel central nesse processo, mas enfrentaram, ao lado do crescimento, um aumento das desigualdades sociais internas, como a marginalização de povos indígenas, negros e outras populações vulneráveis. Esses grupos foram os mais afetados pelas mudanças no uso do território e pela exploração dos recursos naturais em nome da eficiência econômica. O conceito de "racismo ambiental" surge para descrever a exclusão e exploração dessas populações, que sofrem as consequências de uma economia globalizada e voltada para o lucro, sem considerar os impactos ambientais e sociais negativos.
            A colonialidade, conceito desenvolvido por Aníbal Quijano, é outro ponto importante no texto. Ela refere-se ao legado de relações desiguais estabelecidas durante a colonização, cujos efeitos perduram na organização do poder e das relações sociais atuais. O conceito de "raça" como uma construção social também é central na análise, já que foi utilizado para legitimar a exploração e dominação das populações colonizadas. A racialização das relações de poder, de acordo com Quijano, continua a ser um pilar do capitalismo moderno, onde grupos marginalizados são subjugados a formas de exploração que perpetuam a desigualdade social e racial.
            Além disso, o texto aborda a relação entre o crescimento econômico e a degradação ambiental, destacando como a expansão das atividades econômicas, especialmente a mineração e a agricultura industrial, resulta em "zonas de sacrifício" – áreas onde os impactos ambientais e sociais são concentrados nas populações mais vulneráveis. O conceito de "zonas de sacrifício", proposto por Svampa, descreve como territórios indígenas e outras áreas com grande biodiversidade são desqualificados e tornados alvo de projetos de exploração, como a mineração, sem levar em consideração os direitos e as necessidades das comunidades locais.
            Por fim, a análise aponta que, embora a Constituição Brasileira de 1988 tenha avançado no reconhecimento dos direitos dos povos indígenas e na proteção ambiental, a prática continua a marginalizar essas populações. A exploração desses territórios é uma manifestação clara do racismo ambiental, onde as camadas sociais mais baixas são as mais afetadas pelos danos ambientais, como a poluição e a destruição de habitats naturais. O racismo ambiental, portanto, é uma forma de continuar a dominação colonial, mas com novos contornos, em um sistema capitalista global que explora as disparidades sociais e raciais em nome do progresso econômico.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive">
            Environmental Racism: Coloniality in the Exploitation of Territory
          </button>
        </h2>
        <div id="panelsStayOpen-collapseFive" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em inglês.</strong> The text discusses the rise of neoliberalism in the 1990s and 2000s, a period during which global capitalism went through a phase of superaccumulation and reorganization, characterized by the diminishing role of the state in social areas and the promotion of free markets and global consumption. During this period, public policies were devalued, with cuts in social spending such as health, education, and public safety, resulting in greater social inequality and poverty in various regions, despite global economic growth. At the same time, environmental destruction intensified, with the uncontrolled exploitation of natural resources, especially in peripheral countries, leading to increased greenhouse gas emissions and a significant impact on global warming.
            Neoliberalism consolidated itself through the promotion of a borderless market economy, encouraged by globalization and technological advances. Major emerging economies, such as Brazil, Russia, India, and China, played a central role in this process. However, alongside growth, these countries faced an increase in internal social inequalities, such as the marginalization of Indigenous peoples, Black people, and other vulnerable populations. These groups were the most affected by changes in land use and the exploitation of natural resources in the name of economic efficiency. The concept of "environmental racism" emerged to describe the exclusion and exploitation of these populations, who bear the consequences of a globalized, profit-driven economy, without consideration of the negative environmental and social impacts.
            Coloniality, a concept developed by Aníbal Quijano, is another key point in the text. It refers to the legacy of unequal relationships established during colonization, whose effects persist in the organization of power and social relations today. The concept of "race" as a social construct is also central to the analysis, as it was used to legitimize the exploitation and domination of colonized populations. According to Quijano, the racialization of power relations continues to be a pillar of modern capitalism, where marginalized groups are subjected to forms of exploitation that perpetuate social and racial inequality.
            Additionally, the text addresses the relationship between economic growth and environmental degradation, highlighting how the expansion of economic activities, especially mining and industrial agriculture, results in "sacrifice zones"—areas where environmental and social impacts are concentrated on the most vulnerable populations. The concept of "sacrifice zones," proposed by Svampa, describes how Indigenous territories and other areas with rich biodiversity are disqualified and targeted for exploitation projects, such as mining, without considering the rights and needs of local communities.
            Finally, the analysis points out that, although the Brazilian Constitution of 1988 made significant progress in recognizing the rights of Indigenous peoples and environmental protection, in practice, these populations continue to be marginalized. The exploitation of these territories is a clear manifestation of environmental racism, where the lower social classes are the most affected by environmental damage, such as pollution and the destruction of natural habitats. Environmental racism, therefore, is a way to continue colonial domination, but with new contours, in a global capitalist system that exploits social and racial disparities in the name of economic progress.          
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSix" aria-expanded="false" aria-controls="panelsStayOpen-collapseSix">
            Racismo Ambiental: Colonialidad en la Explotación Territorial
          </button>
        </h2>
        <div id="panelsStayOpen-collapseSix" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em espanhol.</strong> El texto analiza el ascenso del neoliberalismo en las décadas de 1990 y 2000, un período en el que el capitalismo global experimentó una fase de sobreacumulación y reorganización, caracterizada por la disminución del papel del Estado en áreas sociales y el estímulo de los mercados libres y el consumo a un ritmo acelerado. escala mundial. Durante este período, las políticas públicas comenzaron a devaluarse, con recortes en el gasto social como salud, educación y seguridad pública, lo que resultó en mayor desigualdad social y pobreza en varias regiones, a pesar del crecimiento económico global. Al mismo tiempo, se ha intensificado la destrucción ambiental, con la explotación desenfrenada de los recursos naturales, especialmente en los países periféricos, lo que ha generado un aumento de las emisiones de gases de efecto invernadero y un impacto significativo en el calentamiento global.
            El neoliberalismo se consolidó con la promoción de una economía de mercado sin fronteras, estimulada por la globalización y el avance tecnológico. Las grandes economías emergentes, como Brasil, Rusia, India y China, desempeñaron un papel central en este proceso, pero enfrentaron, junto con el crecimiento, un aumento de las desigualdades sociales internas, como la marginación de los pueblos indígenas, los negros y otras poblaciones vulnerables. Estos grupos fueron los más afectados por los cambios en el uso del territorio y la explotación de los recursos naturales en nombre de la eficiencia económica. El concepto de "racismo ambiental" surge para describir la exclusión y explotación de estas poblaciones, que sufren las consecuencias de una economía globalizada y con fines de lucro, sin considerar los impactos ambientales y sociales negativos.
            La colonialidad, concepto desarrollado por Aníbal Quijano, es otro punto importante del texto. Se refiere al legado de relaciones desiguales establecidas durante la colonización, cuyos efectos persisten en la organización del poder y las relaciones sociales actuales. El concepto de "raza" como construcción social también es central para el análisis, ya que fue utilizado para legitimar la explotación y dominación de las poblaciones colonizadas. La racialización de las relaciones de poder, según Quijano, sigue siendo un pilar del capitalismo moderno, donde los grupos marginados son subyugados a formas de explotación que perpetúan la desigualdad social y racial.
            Además, el texto aborda la relación entre el crecimiento económico y la degradación ambiental, destacando cómo la expansión de las actividades económicas, especialmente la minería y la agricultura industrial, da como resultado "zonas de sacrificio", áreas donde los impactos ambientales y sociales se concentran en las poblaciones más vulnerables. El concepto de "zonas de sacrificio", propuesto por Svampa, describe cómo los territorios indígenas y otras áreas con gran biodiversidad son descalificados y convertidos en blanco de proyectos de exploración, como la minería, sin tener en cuenta los derechos y necesidades de las comunidades locales.
            Finalmente, el análisis señala que, si bien la Constitución brasileña de 1988 ha avanzado en el reconocimiento de los derechos de los pueblos indígenas y la protección del medio ambiente, la práctica continúa marginando a estas poblaciones. La explotación de estos territorios es una clara manifestación de racismo ambiental, donde los estratos sociales más bajos son los más afectados por los daños ambientales, como la contaminación y la destrucción de hábitats naturales. El racismo ambiental, por lo tanto, es una forma de continuar la dominación colonial, pero con nuevos contornos, en un sistema capitalista global que explota las disparidades sociales y raciales en nombre del progreso económico.
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSeven" aria-expanded="false" aria-controls="panelsStayOpen-collapseSeven">
            Racismo Ambiental: Necropolítica, Periferia e Epidemiologia
          </button>
        </h2>
        <div id="panelsStayOpen-collapseSeven" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em português.</strong> O conceito de racismo ambiental refere-se à discriminação racial nas políticas ambientais, que resultam na escolha deliberada de comunidades marginalizadas para receberem resíduos tóxicos e instalações poluidoras, afetando principalmente populações negras, indígenas, quilombolas e outras comunidades vulneráveis.
            A necropolítica é discutida como uma política de morte que afeta esses grupos, colocando-os em risco pela negligência do Estado e pela aplicação desigual das políticas públicas. O artigo destaca que as comunidades periféricas sofrem com a falta de infraestrutura básica e a exposição a riscos ambientais, o que amplifica as desigualdades sociais e de saúde. Exemplo disso é a tragédia de Mariana, em 2015, que atingiu em maior medida pessoas negras, revelando o vínculo entre racismo e desastre ambiental.
            Além disso, a pandemia de COVID-19 exacerbou essas desigualdades. As populações em situação de vulnerabilidade enfrentam dificuldades como o acesso limitado à saúde e saneamento básico inadequado, o que agrava a disseminação do vírus e o impacto da doença. A falta de políticas públicas eficazes para esses grupos é um reflexo do racismo institucionalizado, que ignora as necessidades dessas comunidades.
            Por fim, o texto propõe que, para combater o racismo ambiental e suas consequências, é essencial garantir a participação ativa das comunidades afetadas na formulação de políticas de saúde e ambientais, respeitando suas especificidades culturais e sociais. O artigo enfatiza a urgência de reconhecer e tratar as populações vulneráveis de maneira equitativa, em vez de reforçar sua marginalização.          
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseEight" aria-expanded="false" aria-controls="panelsStayOpen-collapseEight">
            Environmental Racism: Necropolitics, Periphery, and Epidemiology
          </button>
        </h2>
        <div id="panelsStayOpen-collapseEight" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em inglês.</strong> The concept of environmental racism refers to racial discrimination in environmental policies that result in the deliberate targeting of marginalized communities for the disposal of toxic waste and the establishment of polluting facilities, primarily affecting Black, Indigenous, quilombola, and other vulnerable populations.
            Necropolitics is discussed as a policy of death that affects these groups, putting them at risk due to state neglect and the unequal implementation of public policies. The article highlights that peripheral communities suffer from a lack of basic infrastructure and exposure to environmental risks, which exacerbates social and health inequalities. One example is the 2015 Mariana tragedy, which disproportionately affected Black people, revealing the link between racism and environmental disaster.
            Additionally, the COVID-19 pandemic exacerbated these inequalities. Vulnerable populations faced challenges such as limited access to healthcare and inadequate sanitation, which worsened the spread of the virus and the impact of the disease. The lack of effective public policies for these groups reflects institutionalized racism that ignores the needs of these communities.
            Finally, the text suggests that to combat environmental racism and its consequences, it is essential to ensure the active participation of affected communities in the formulation of health and environmental policies, respecting their cultural and social specificities. The article emphasizes the urgency of recognizing and addressing vulnerable populations equitably, rather than reinforcing their marginalization.          
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseNine" aria-expanded="false" aria-controls="panelsStayOpen-collapseNine">
            Racismo Ambiental: Necropolítica, Periferia y Epidemiología
          </button>
        </h2>
        <div id="panelsStayOpen-collapseNine" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em espanhol.</strong> El concepto de racismo ambiental se refiere a la discriminación racial en las políticas ambientales, que resultan en la elección deliberada de comunidades marginadas de recibir desechos tóxicos e instalaciones contaminantes, afectando principalmente a comunidades negras, indígenas, quilombolas y otras comunidades vulnerables.
            Se discute la necropolítica como una política de muerte que afecta a estos grupos, poniéndolos en riesgo por la negligencia del Estado y la aplicación desigual de las políticas públicas. El artículo destaca que las comunidades periféricas sufren de falta de infraestructura básica y exposición a riesgos ambientales, lo que amplifica las desigualdades sociales y sanitarias. Un ejemplo de esto es la tragedia de Mariana, en 2015, que afectó en mayor medida a los negros, revelando el vínculo entre racismo y desastre ambiental.
            Además, la pandemia de COVID-19 ha exacerbado estas desigualdades. Las poblaciones en situaciones vulnerables enfrentan dificultades como un acceso limitado a la atención médica y un saneamiento básico inadecuado, lo que empeora la propagación del virus y el impacto de la enfermedad. La falta de políticas públicas efectivas para estos grupos es un reflejo del racismo institucionalizado, que ignora las necesidades de estas comunidades.
            Finalmente, el texto propone que, para combatir el racismo ambiental y sus consecuencias, es esencial garantizar la participación activa de las comunidades afectadas en la formulación de políticas sanitarias y ambientales, respetando sus especificidades culturales y sociales. El artículo enfatiza la urgencia de reconocer y tratar a las poblaciones vulnerables de manera equitativa, en lugar de reforzar su marginación.
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTen" aria-expanded="false" aria-controls="panelsStayOpen-collapseTen">
            Da negação da cidadania para o império da biopolítica: pilares do racismo ambiental
          </button>
        </h2>
        <div id="panelsStayOpen-collapseTen" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em português.</strong> Racismo ambiental é descrito como um fenômeno de injustiças sociais e ambientais direcionadas a grupos étnicos vulneráveis, sendo uma manifestação do biopoder, um conceito elaborado por Michel Foucault. A biopolítica, desde o século XVIII, envolve o controle da vida e dos corpos, com foco em otimizar as forças humanas, ao contrário do poder soberano, que visava “fazer morrer”. O biopoder, portanto, age não apenas controlando os corpos individuais, mas também a vida coletiva, regulando nascimentos, saúde, longevidade, entre outros.
            A relação entre racismo ambiental e biopolítica é evidente quando se observa que a privação de direitos sociais, como acesso à saúde, educação e moradia, é uma estratégia do Estado que mantém a marginalização desses grupos. O racismo ambiental, então, é visto como uma forma de exclusão cidadã e uma extensão da biopolítica, que, ao não garantir a justiça social para todos os grupos étnicos, implica em um controle governamental que, muitas vezes, promove a morte simbólica ou física dessas populações.
            Além disso, o texto menciona a necropolítica de Achille Mbembe, que se refere a políticas de morte direcionadas aos não-brancos e a resistência dos movimentos negros nos Estados Unidos, que surgiram como resposta ao racismo ambiental. No Brasil, o Movimento Negro Brasileiro (MNB) desempenha um papel fundamental na luta contra o racismo e na promoção da inclusão socioespacial, buscando garantir o acesso à cidadania e à dignidade de vida, especialmente para as populações negras e indígenas.
            Em resumo, o texto explora como a biopolítica e o racismo ambiental convergem para a marginalização e eliminação de grupos vulneráveis, propondo como solução a resistência organizada e a busca pela igualdade social e territorial.
            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseEleven" aria-expanded="false" aria-controls="panelsStayOpen-collapseEleven">
            The Denial of Citizenship for the Empire of Biopolitics: Pillars of Environmental Racism
          </button>
        </h2>
        <div id="panelsStayOpen-collapseEleven" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em inglês.</strong> Environmental racism is described as a phenomenon of social and environmental injustices directed at vulnerable ethnic groups, being a manifestation of biopower, a concept developed by Michel Foucault. Biopolitics, since the 18th century, involves the control of life and bodies, focusing on optimizing human forces, in contrast to sovereign power, which aimed to "make die." Biopower, therefore, acts not only by controlling individual bodies but also by regulating collective life, such as births, health, longevity, among others.
            The relationship between environmental racism and biopolitics is evident when observing that the deprivation of social rights, such as access to health, education, and housing, is a state strategy that maintains the marginalization of these groups. Environmental racism is thus seen as a form of citizenship exclusion and an extension of biopolitics, which, by failing to ensure social justice for all ethnic groups, entails governmental control that often promotes the symbolic or physical death of these populations.
            Furthermore, the text mentions Achille Mbembe's concept of necropolitics, referring to death policies targeted at non-white populations, and the resistance of Black movements in the United States, which emerged as a response to environmental racism. In Brazil, the Movimento Negro Brasileiro (Brazilian Black Movement - MNB) plays a fundamental role in the fight against racism and in promoting socio-spatial inclusion, seeking to ensure access to citizenship and a dignified life, especially for Black and Indigenous populations.
            In summary, the text explores how biopolitics and environmental racism converge to marginalize and eliminate vulnerable groups, proposing organized resistance and the pursuit of social and territorial equality as a solution.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwelve" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwelve">
            De la negación de la ciudadanía al imperio de la biopolítica: pilares del racismo ambiental
          </button>
        </h2>
        <div id="panelsStayOpen-collapseTwelve" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em espanhol.</strong> El racismo ambiental se describe como un fenómeno de injusticias sociales y ambientales dirigido a grupos étnicos vulnerables, siendo una manifestación del biopoder, concepto elaborado por Michel Foucault.  La biopolítica, desde el siglo XVIII, implica el control de la vida y los cuerpos, con un enfoque en la optimización de las fuerzas humanas, a diferencia del poder soberano, que apuntaba a “hacer morir a la gente”.  El biopoder, por tanto, actúa no sólo para controlar los cuerpos individuales, sino también la vida colectiva, regulando los nacimientos, la salud, la longevidad, entre otros.
            La relación entre racismo ambiental y biopolítica se evidencia cuando se observa que la privación de derechos sociales, como el acceso a la salud, la educación y la vivienda, es una estrategia de Estado que mantiene la marginación de estos grupos.  El racismo ambiental, entonces, es visto como una forma de exclusión ciudadana y una extensión de la biopolítica, que, al no garantizar la justicia social para todos los grupos étnicos, implica un control gubernamental que muchas veces promueve la muerte simbólica o física de estas poblaciones.
            Además, el texto menciona la necropolítica de Achille Mbembe, que se refiere a las políticas de muerte dirigidas a los no blancos y a la resistencia de los movimientos negros en Estados Unidos, que surgieron como respuesta al racismo ambiental.  En Brasil, el Movimiento Negro Brasileño (MNB) juega un papel fundamental en la lucha contra el racismo y en la promoción de la inclusión socioespacial, buscando garantizar el acceso a la ciudadanía y la dignidad de vida, especialmente para las poblaciones negras e indígenas.
            En definitiva, el texto explora cómo la biopolítica y el racismo ambiental convergen hacia la marginación y eliminación de grupos vulnerables, proponiendo como solución la resistencia organizada y la búsqueda de la igualdad social y territorial.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThirteen" aria-expanded="false" aria-controls="panelsStayOpen-collapseThirteen">
            Racismo ambiental e o princípio do meio ambiente ecologicamente equilibrado
          </button>
        </h2>
        <div id="panelsStayOpen-collapseThirteen" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em português.</strong> Para lidar com os problemas ambientais, é essencial a aplicação dos princípios da justiça ambiental sustentável. Quando esses princípios são seguidos, pode-se alcançar uma sociedade que se preocupa com questões ambientais, promovendo uma realidade de ética e moral ambiental sustentável. No contexto do direito ecológico, as relações raciais e a discriminação ambiental, conforme o artigo 225 da Constituição Federal de 1988, o meio ambiente é considerado um bem coletivo e essencial para a vida, sendo responsabilidade do Estado e das pessoas defendê-lo para as futuras gerações. A Constituição também garante a legitimidade dos cidadãos para denunciarem atos que prejudicam o meio ambiente e estabelece terras fluviais, ilhas oceânicas e costeiras como bens da União. Além disso, o Estado, os Estados e o Distrito Federal são responsáveis por legislar sobre questões ambientais, e a defesa do meio ambiente deve ser diferenciada conforme o tipo de dano ambiental.
            Os princípios do Direito Ambiental, embora muitas vezes gerais, orientam a aplicação das normas, sendo fundamentais para garantir a sustentabilidade. A sistematização desses princípios inclui o direito de acesso equitativo aos recursos naturais, o princípio do usuário-pagador, da precaução, da prevenção, da reparação, da participação e da informação. O princípio do acesso equitativo aos recursos naturais garante o direito de acesso a recursos de forma razoável, sem causar danos ambientais irreversíveis, visando a proteção do meio ambiente para as futuras gerações. O princípio do usuário-pagador impõe sanções a quem gera danos ambientais, enquanto o princípio da precaução e da prevenção alertam sobre atividades que possam ameaçar o meio ambiente, com foco na prevenção de danos conhecidos e desconhecidos. Quando o dano ocorre, o princípio da reparação entra em ação, determinando a responsabilidade pelo reparo dos danos ambientais. O princípio da informação tem como objetivo sensibilizar a população sobre os danos ambientais, enquanto o princípio da participação permite que a população atue ativamente na fiscalização e proteção ambiental.
            A Constituição de 1988 garante um meio ambiente ecologicamente equilibrado como um direito fundamental, influenciando outras legislações. Este direito não é apenas programático, mas sim um direito fundamental que exige a atuação do Estado, tanto como fiscalizador quanto legislador. O conceito de meio ambiente equilibrado gerou uma colisão de direitos, demandando uma relação ponderada entre eles. Além disso, o autor defende que a aplicação do conceito de meio ambiente equilibrado deve ser feita de maneira equilibrada, considerando a ética ambiental e os direitos constitucionais, promovendo justiça ambiental e redução de desigualdades sociais.
            A justiça ambiental e o socioambientalismo têm um papel importante na criação de um desenvolvimento sustentável. A Conferência Rio +20 (2012) trouxe novas abordagens para as políticas ambientais no Brasil, destacando a importância da justiça socioambiental. Para que o Brasil adote essas novas perspectivas, o Direito Ambiental deve caminhar na direção de desenvolver e consolidar políticas públicas, com base na Constituição Federal, fortalecendo a relação entre o ambiente e a sociedade. O Brasil, por ser um país com grande extensão territorial e com parte da floresta amazônica, precisa adotar novas políticas de conscientização ambiental. Isso se reflete também na aplicação de experiências jurídicas que já funcionam em países europeus e no Direito Ambiental Internacional, influenciando diretamente a abordagem de justiça ambiental brasileira.
            Esse novo sistema socioambiental no Brasil é fundamentado em três pilares principais: a eficácia econômica, que defende o uso de recursos naturais para o desenvolvimento das atividades econômicas; a proteção do meio ambiente, com a obrigação do Estado de protegê-lo; e a equidade social, garantindo a todos os cidadãos acesso a um ambiente saudável e condições dignas de vida. A ideia é criar uma nova abordagem para o direito ambiental, levando em conta as diferenças culturais do Brasil e a necessidade de preservar as diversas etnias do país.
            O desenvolvimento sustentável exige uma mudança de paradigmas no Brasil, considerando a importância de manter o equilíbrio entre desenvolvimento econômico e proteção ambiental. A implementação de políticas públicas ambientais pode combater o racismo ambiental e promover a multiculturalidade, respeitando as diferentes culturas presentes no Brasil. Isso ajuda a garantir a sustentabilidade e qualidade de vida para todos, combatendo práticas que prejudicam o meio ambiente, como a exploração de terras indígenas e de povos tradicionais. Dessa forma, é possível construir uma nova ideia de direitos sustentáveis, moldada pela política pública, transformando a relação do ser humano com o meio ambiente e utilizando a justiça ambiental para moldar um novo direito de sustentabilidade.
            Entretanto, a aplicação plena desse novo modelo enfrenta obstáculos, pois não se trata de uma solução imediata, mas de um desenvolvimento gradual. A falta de implementação de certos direitos na legislação pode distorcer os princípios constitucionais fundamentais, dificultando a aplicação dos direitos ambientais e a promoção da sustentabilidade. O racismo ambiental, que ainda é uma questão relevante, foi discutido na COP 27 em 2022, especialmente em relação à preservação das reservas indígenas e quilombolas no Brasil, um país que sofre com a desigualdade social. Dessa forma, as lutas ambientais estão cada vez mais ligadas às questões sociais e raciais, com o objetivo de garantir um meio ambiente mais justo e equitativo para todas as populações, especialmente as mais vulneráveis.            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFourteen" aria-expanded="false" aria-controls="panelsStayOpen-collapseFourteen">
            Environmental Racism and the Principle of an Ecologically Balanced Environment
          </button>
        </h2>
        <div id="panelsStayOpen-collapseFourteen" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em ingles.</strong> Addressing environmental issues requires the application of the principles of sustainable environmental justice. When these principles are adhered to, a society that prioritizes environmental concerns can be achieved, promoting an ethical and sustainable environmental reality. In the context of ecological law, racial relations and environmental discrimination are defined by Article 225 of the 1988 Brazilian Constitution, which considers the environment a collective and essential resource for life. It is the responsibility of both the State and individuals to protect it for future generations. The Constitution also grants citizens the legitimacy to report actions that harm the environment and establishes river lands, oceanic islands, and coastal areas as public property. Additionally, the State, Federal States, and the Federal District are responsible for legislating on environmental matters, with environmental protection differentiated according to the type of damage caused.
            Environmental Law principles, though often broad, guide the application of regulations and are crucial for ensuring sustainability. The systematization of these principles includes the right to equitable access to natural resources, the polluter-pays principle, precaution, prevention, remediation, participation, and information. The principle of equitable access to natural resources guarantees reasonable access to resources without causing irreversible environmental harm, aiming to protect the environment for future generations. The polluter-pays principle imposes sanctions on those responsible for environmental damage, while the principles of precaution and prevention caution against activities that may endanger the environment, focusing on preventing both known and unknown harms. When damage occurs, the principle of remediation ensures responsibility for repairing environmental harm. The information principle seeks to raise public awareness of environmental damage, and the participation principle empowers the population to actively engage in environmental monitoring and protection.
            The 1988 Constitution enshrines an ecologically balanced environment as a fundamental right, influencing other legislations. This right is not just programmatic but demands action from the State, both as a regulator and legislator. The concept of a balanced environment has led to a clash of rights, requiring a nuanced relationship between them. The author argues that the application of this concept must be balanced, considering environmental ethics and constitutional rights, promoting environmental justice and reducing social inequalities.
            Environmental justice and socio-environmentalism play a key role in fostering sustainable development. The Rio +20 Conference (2012) introduced new approaches to environmental policies in Brazil, highlighting the importance of socio-environmental justice. To adopt these new perspectives, Environmental Law in Brazil must evolve to develop and consolidate public policies based on the Federal Constitution, strengthening the connection between the environment and society. Brazil, with its vast territorial expanse and part of the Amazon rainforest, needs to adopt new environmental awareness policies. This is reflected in the application of legal practices in European countries and in International Environmental Law, which directly influence Brazil's approach to environmental justice.
            This new socio-environmental system in Brazil rests on three main pillars: economic efficiency, which supports the use of natural resources for economic development; environmental protection, with the State's duty to safeguard it; and social equity, ensuring all citizens access to a healthy environment and dignified living conditions. The aim is to create a new framework for environmental law, recognizing Brazil's cultural diversity and the necessity of preserving the country’s varied ethnic groups.
            Sustainable development requires a paradigm shift in Brazil, taking into account the importance of balancing economic development with environmental protection. The implementation of environmental public policies can address environmental racism and promote multiculturalism, respecting the various cultures within Brazil. This would help ensure sustainability and quality of life for all, combating practices that harm the environment, such as the exploitation of indigenous and traditional peoples' lands. Thus, a new vision of sustainable rights can be created, shaped by public policy, transforming the human-environment relationship and using environmental justice to forge a new legal approach to sustainability.
            However, fully implementing this new model faces challenges, as it is not an immediate fix but a gradual process. The lack of full legal enforcement of certain rights may distort fundamental constitutional principles, hindering the application of environmental rights and the promotion of sustainability. Environmental racism, still a significant issue, was discussed at COP 27 in 2022, especially regarding the preservation of indigenous and quilombola reserves in Brazil, a country plagued by social inequality. Consequently, environmental struggles are increasingly intertwined with social and racial issues, aiming to ensure a fairer and more equitable environment for all, particularly the most vulnerable populations.            
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button fw-bold text-uppercase collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFifteen" aria-expanded="false" aria-controls="panelsStayOpen-collapseFifteen">
            El racismo ambiental y el principio de un medio ambiente ecológicamente equilibrado
          </button>
        </h2>
        <div id="panelsStayOpen-collapseFifteen" class="accordion-collapse collapse">
          <div class="accordion-body">
            <strong>Trecho de artigo em espanhol.</strong> Para abordar los problemas ambientales, es esencial aplicar los principios de justicia ambiental sostenible.  Cuando se siguen estos principios, se puede lograr una sociedad que se preocupe por las cuestiones ambientales, promoviendo una realidad de ética y moral ambiental sostenible.  En el contexto del derecho ecológico, las relaciones raciales y la discriminación ambiental, según el artículo 225 de la Constitución Federal de 1988, el medio ambiente es considerado un bien colectivo y esencial para la vida, y es responsabilidad del Estado y del pueblo defenderlo para el generaciones futuras.  La Constitución también garantiza la legitimidad de los ciudadanos para denunciar actos que dañen el medio ambiente y establece como bienes de la Unión las tierras fluviales, las islas oceánicas y costeras. Además, el Estado, los Estados y el Distrito Federal son responsables de legislar en materia ambiental y de protección del medio ambiente. deben diferenciarse según el tipo de daño ambiental.
            Los principios del Derecho Ambiental, aunque muchas veces generales, guían la aplicación de las normas, siendo fundamentales para asegurar la sostenibilidad.  La sistematización de estos principios incluye el derecho al acceso equitativo a los recursos naturales, el principio de quien paga, la precaución, la prevención, la reparación, la participación y la información.  El principio de acceso equitativo a los recursos naturales garantiza el derecho a acceder a los recursos de manera razonable, sin causar daños ambientales irreversibles, con el objetivo de proteger el medio ambiente para las generaciones futuras.  El principio de que el usuario paga impone sanciones a quienes causan daños ambientales, mientras que los principios de precaución y prevención advierten sobre actividades que pueden amenazar el medio ambiente, con un enfoque en prevenir daños conocidos y desconocidos.  Cuando se produce un daño entra en juego el principio de reparación, determinando la responsabilidad de reparar el daño ambiental.  El principio de información tiene como objetivo sensibilizar a la población sobre los daños ambientales, mientras que el principio de participación permite a la población actuar activamente en la supervisión y protección ambiental.
            La Constitución de 1988 garantiza un medio ambiente ecológicamente equilibrado como derecho fundamental, influyendo en otras legislaciones.  Este derecho no es sólo programático, sino un derecho fundamental que requiere que el Estado actúe, a la vez como supervisor y legislador.  El concepto de ambiente equilibrado generó una colisión de derechos, exigiendo una relación considerada entre ellos.  Además, el autor sostiene que la aplicación del concepto de medio ambiente equilibrado debe hacerse de manera equilibrada, considerando la ética ambiental y los derechos constitucionales, promoviendo la justicia ambiental y reduciendo las desigualdades sociales.
            La justicia ambiental y el socioambientalismo desempeñan un papel importante en la creación de un desarrollo sostenible.  La Conferencia Río +20 (2012) trajo nuevos enfoques a las políticas ambientales en Brasil, destacando la importancia de la justicia socioambiental.  Para que Brasil adopte estas nuevas perspectivas, el Derecho Ambiental debe avanzar hacia el desarrollo y consolidación de políticas públicas, basadas en la Constitución Federal, fortaleciendo la relación entre el medio ambiente y la sociedad.  Brasil, como país con una gran extensión territorial y parte de la selva amazónica, necesita adoptar nuevas políticas de conciencia ambiental.  Esto también se refleja en la aplicación de experiencias jurídicas que ya funcionan en países europeos y en Derecho Ambiental Internacional, influyendo directamente en el enfoque brasileño de justicia ambiental.
            Este nuevo sistema socioambiental en Brasil se basa en tres pilares principales: la eficiencia económica, que defiende el uso de los recursos naturales para el desarrollo de actividades económicas;  la protección del medio ambiente, con la obligación del Estado de protegerlo;  y equidad social, garantizando a todos los ciudadanos el acceso a un medio ambiente sano y a condiciones de vida dignas.  La idea es crear un nuevo enfoque del derecho ambiental, teniendo en cuenta las diferencias culturales de Brasil y la necesidad de preservar las diversas etnias del país.
            El desarrollo sostenible requiere un cambio de paradigmas en Brasil, considerando la importancia de mantener un equilibrio entre el desarrollo económico y la protección del medio ambiente.  La implementación de políticas públicas ambientales puede combatir el racismo ambiental y promover el multiculturalismo, respetando las diferentes culturas presentes en Brasil.  Esto ayuda a garantizar la sostenibilidad y la calidad de vida para todos, combatiendo prácticas que dañan el medio ambiente, como la explotación de tierras indígenas y pueblos tradicionales.  De esta manera, es posible construir una nueva idea de derechos sostenibles, moldeada por políticas públicas, transformando la relación entre los seres humanos y el medio ambiente y utilizando la justicia ambiental para configurar un nuevo derecho a la sostenibilidad.
           Sin embargo, la plena aplicación de este nuevo modelo enfrenta obstáculos, ya que no se trata de una solución inmediata, sino de un desarrollo gradual.  La falta de implementación de ciertos derechos en la legislación puede distorsionar principios constitucionales fundamentales, dificultando la aplicación de los derechos ambientales y la promoción de la sostenibilidad.  El racismo ambiental, que sigue siendo un tema relevante, fue discutido en la COP 27 de 2022, especialmente en relación con la preservación de las reservas indígenas y quilombolas en Brasil, un país que sufre desigualdad social.  De esta manera, las luchas medioambientales están cada vez más vinculadas a cuestiones sociales y raciales, con el objetivo de garantizar un entorno más justo y equitativo para todas las poblaciones, especialmente las más vulnerables.
          </div>
        </div>
      </div>
  </div>
</div>
@endsection